### ISSUE TITLE
Tasks 2.9.1

### ISSUE THREAD

**Issue by pkrall520** [irrationalistic/atom-tasks#92] opened 2018-02-15 19:54 UTC
this.registry.startIdForScope is not a function
Hide Stack Trace
TypeError: this.registry.startIdForScope is not a function
    at Grammar.module.exports.Grammar.startIdForScope (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\node_modules\first-mate\lib\grammar.js:324:34)
    at TextMateLanguageMode.tokenizedLineForRow (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\text-mate-language-mode.js:428:30)
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\node_modules\bracket-matcher\lib\tag-finder.js:53:36)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\node_modules\bracket-matcher\lib\tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\node_modules\bracket-matcher\lib\tag-finder.js:207:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\node_modules\bracket-matcher\lib\bracket-matcher-view.js:126:41)
    at C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\node_modules\bracket-matcher\lib\bracket-matcher-view.js:3:65
    at buffer.onDidChangeLanguageMode (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor.js:741:13)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.setLanguageMode (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1373:28)
    at grammarScoresByBuffer.forEach (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\grammar-registry.js:300:22)
    at Map.forEach (native)
    at GrammarRegistry.grammarAddedOrUpdated (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\grammar-registry.js:287:38)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\node_modules\first-mate\lib\grammar-registry.js:80:26)
    at GrammarRegistry.addGrammar (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\grammar-registry.js:355:40)
    at Object.updateGrammar (file:///C:/Users/Phillip Krall/.atom/packages/tasks/lib/tasks.coffee:125:19)
    at file:///C:/Users/Phillip Krall/.atom/packages/tasks/lib/tasks.coffee:54:22
    at Config.module.exports.Config.observeKeyPath (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\config.js:674:13)
    at Config.module.exports.Config.observe (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\config.js:155:27)
    at Object.activate (file:///C:/Users/Phillip Krall/.atom/packages/tasks/lib/tasks.coffee:53:17)
    at Package.activateNow (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\package.js:230:33)
    at measure (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\package.js:206:33)
    at Package.measure (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\package.js:88:25)
    at activationPromise.Promise (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\package.js:200:20)
    at Package.activate (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\package.js:198:38)
    at PackageManager.activatePackage (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\package-manager.js:695:42)
    at packagesToEnable.forEach.name (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\package-manager.js:440:30)
    at C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\config.js:884:35)
    at Config.module.exports.Config.setRawValue (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\config.js:670:25)
    at Config.module.exports.Config.set (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\config.js:407:18)
    at Package.enable (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\package.js:75:30)
    at PackageManager.enablePackage (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\src\package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (C:\Users\Phillip Krall\AppData\Local\atom\app-1.24.0\resources\app\node_modules\settings-view\lib\package-card.js:361:31)
The error was thrown from the tasks package. This issue has already

**Comment by irrationalistic** [comment] 2018-02-16 06:32
This is a duplicate of #88 and has been fixed in the recent commit!

**Closed by irrationalistic** 2018-02-16 06:32 UTC
Labels: duplicate
