### ISSUE TITLE
Add syntax highlighting for basic tags

### ISSUE THREAD

**Issue by tobkum** [irrationalistic/atom-tasks#91] opened 2018-01-08 12:46 UTC
It would be a great visual help to highlight some tags in a special color, such as @critical, @high and @low
Right now all tags are colored uniformly, which doesn't help judging the importance.
See the attached screenshot taken from https://github.com/sandy081/vscode-todotasks

![image](https://user-images.githubusercontent.com/16955378/34671257-2b9108ec-f47a-11e7-8761-a89cccb3c977.png)

**Comment by irrationalistic** [comment] 2018-02-16 06:59
This is a duplicate of #48, so take a look there! Essentially, each tag is given an automatic wrapping classname that is represented by the content of the tag title, so you should be able to apply your own custom styles! Closing this for now, but let me know if that's not helpful.

**Closed by irrationalistic** 2018-02-16 06:59 UTC
Labels: duplicate
