### ISSUE TITLE
Boolean filtering/search a la Taskpaper

### ISSUE THREAD

**Issue by wakatara** [irrationalistic/atom-tasks#61] opened 2016-10-29 06:56 UTC
## Feature Request 

One feature I'd request if it's at all possible, would be what I think (for me, at least) _makes_ Taskpaper -- the ability to filter in place the taskpaper list via a nice little query:
(ie @week = 43 and not @done in the search) 

Imagine that is by no means trivial, but it is the key thing that makes taskpaper so powerful for me as a GTD app.  =] 

thanks for all your hard work!

**Comment by irrationalistic** [comment] 2016-10-30 07:31
This is a duplicate of #19! I'm definitely interested in exploring this more, though time has been limited :)

**Comment by irrationalistic** [comment] 2016-10-30 07:32
Closing this particular issue in favor of keeping the conversation in one place

**Closed by irrationalistic** 2016-10-30 07:32 UTC
Labels: duplicate
