### ISSUE TITLE
TextEditor.module.exports.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jithu-d** [irrationalistic/atom-tasks#60] opened 2016-09-02 04:58 UTC
`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.
```
TextEditor.module.exports.Object.defineProperty.get (/Users/dbkarthik/Downloads/DMG/Atom.app/Contents/Resources/app.asar/src/text-editor.js:87:14)
status-bar-tasks.subscribeToActiveTextEditor (/Users/dbkarthik/.atom/packages/tasks/lib/views/task-status-view.coffee:50:78)
status-bar-tasks.initialize (/Users/dbkarthik/.atom/packages/tasks/lib/views/task-status-view.coffee:25:19)
Object.consumeStatusBar (/Users/dbkarthik/.atom/packages/tasks/lib/tasks.coffee:189:23)
Provider.provide (/Users/dbkarthik/Downloads/DMG/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
<unknown> (/Users/dbkarthik/Downloads/DMG/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26)
```

**Comment by irrationalistic** [comment] 2016-09-05 05:34
Can you give me a bit more information about how to reproduce this issue? I was unable to get the error to occur! Also, what version are you using?

**Comment by irrationalistic** [comment] 2016-10-30 07:35
Closing as I am unable to reproduce this issue. Feel free to re-open if it comes back!

**Closed by irrationalistic** 2016-10-30 07:35 UTC
