### ISSUE TITLE
Project is no longer being included on completed task lines

### ISSUE THREAD

**Issue by haraldnagel** [irrationalistic/atom-tasks#58] opened 2016-08-03 17:31 UTC
It appears that somewhere around the Atom 1.9.1 release, flagging a task as complete is not adding the `@project()` decoration to the line.

- Atom 1.9.1
- Tasks 2.6.0

Sample file format:
```
Project of awesome:
  - Do this thing
  ✔ Do the other thing @done(2016-08-03 10:30)
```

**Comment by irrationalistic** [comment] 2016-08-05 22:32
I can reproduce this. Will look into it ASAP, thanks for flagging!

**Comment by irrationalistic** [comment] 2016-08-05 23:14
Looks like `indentLevel` was removed as a property on tokenized lines, looking for a fix.

**Comment by irrationalistic** [comment] 2016-08-05 23:34
Closing as this should be fixed now! Feel free to re-open if it crops back up :)

**Closed by irrationalistic** 2016-08-05 23:34 UTC
Labels: bug

**Comment by haraldnagel** [comment] 2016-08-08 18:11
:+1: works great. Thanks so much, this plug-in is very useful!

**Comment by massic80** [comment] 2020-07-02 09:42
I'm having the same issue, four years later: I'm still in time to reopen it? :)
