### ISSUE TITLE
Does it support windows PC?it seems not to work  -_-//

### ISSUE THREAD

**Issue by yalishizhude** [irrationalistic/atom-tasks#52] opened 2016-02-29 09:33 UTC

**Comment by irrationalistic** [comment] 2016-03-02 18:10
Yes, your commands should all work using "ctrl." Have you tried restarting the editor or re-installing the package? Are you getting any errors? Can you send any screenshots of what you mean by it not working?

**Comment by yalishizhude** [comment] 2016-03-03 03:28
I reinstalled the package and then restart atom.There's no any error.I'm not sure if the keys confli
![1](https://cloud.githubusercontent.com/assets/3870098/13483829/0fed7f96-e133-11e5-9863-2129ab2a2ebc.png)
![2](https://cloud.githubusercontent.com/assets/3870098/13483831/15a08596-e133-11e5-9299-9286161a6dc6.png)

ct.
For example,when I pressed ctrl-enter keys,cursor go to a new line instead of tasks working.

**Comment by irrationalistic** [comment] 2016-03-06 17:04
In the editor, try hitting ctrl-. which will turn on the hotkey visualization. When you then hit ctrl-enter, what command is highlighted in green at the bottom?

**Comment by yalishizhude** [comment] 2016-03-07 01:21
I pressed ctrl,but there isn't hotkey visualization.But when I pressed ctrl-shift-P and input "task",I see operations.
It is so pitty without hot key T_T
![Uploading Unnamed QQ Screenshot20160307091913.png…]()

**Comment by irrationalistic** [comment] 2016-03-07 19:09
Agreed! Hotkeys should definitely be working! So try ctrl-shift-P and search for "Keybinding resolver: toggle" and hit that. It should open a panel at the bottom of the screen that will show you what a key combination you type corresponds with. My guess is that another plugin might be vying for attention. Can you toggle the keybinding resolver and then screenshot after hitting ctrl-enter in a tasks file?

**Comment by yalishizhude** [comment] 2016-03-08 09:50
![1](https://cloud.githubusercontent.com/assets/3870098/13597957/35bf7aea-e556-11e5-8e5c-e2cc9782a2fc.png)

**Comment by irrationalistic** [comment] 2016-03-08 17:11
Very odd! Looks like something is failing to match for the proper hotkey to fire. Do any of the other hotkeys work? I'm not at a windows machine right now, but i can check later today to see if i can reproduce the issue.

**Comment by yalishizhude** [comment] 2016-03-09 00:55
Other package's hot key can work~All this package's keys don't work.
atom version: 1.54
system version: windows 10
thx~

**Comment by irrationalistic** [comment] 2016-03-11 04:44
I tested on my own machine and i can't seem to reproduce the issue. This is pretty tough for me to debug! No hotkeys for this package work? It might be a conflict with another package you have installed. Can you send a list of other packages you are running so i can take a look?

**Comment by yalishizhude** [comment] 2016-03-11 14:20
Of course,I'm so sorry to make you tough~
Built-in Atom packages (89)
├── about@1.3.0
├── archive-view@0.61.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.9.2
├── autocomplete-css@0.11.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.25.0
├── autocomplete-snippets@1.9.0
├── autoflow@0.26.0
├── autosave@0.23.0
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.38.0
├── bracket-matcher@0.79.0
├── command-palette@0.38.0
├── deprecation-cop@0.54.0
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.37.0
├── find-and-replace@0.195.0
├── fuzzy-finder@0.94.0
├── git-diff@0.57.0
├── go-to-line@0.30.0
├── grammar-selector@0.48.0
├── image-view@0.56.0
├── incompatible-packages@0.25.0
├── keybinding-resolver@0.33.0
├── language-c@0.51.1
├── language-clojure@0.19.1
├── language-coffee-script@0.46.0
├── language-csharp@0.11.0
├── language-css@0.36.0
├── language-gfm@0.82.0
├── language-git@0.11.0
├── language-go@0.42.0
├── language-html@0.44.0
├── language-hyperlink@0.16.0
├── language-java@0.17.0
├── language-javascript@0.105.0
├── language-json@0.17.3
├── language-less@0.29.0
├── language-make@0.21.0
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.32.0
├── language-php@0.36.0
├── language-property-list@0.8.0
├── language-python@0.43.0
├── language-ruby@0.68.0
├── language-ruby-on-rails@0.25.0
├── language-sass@0.45.0
├── language-shellscript@0.21.0
├── language-source@0.9.0
├── language-sql@0.20.0
├── language-text@0.7.0
├── language-todo@0.27.0
├── language-toml@0.18.0
├── language-xml@0.34.2
├── language-yaml@0.25.0
├── line-ending-selector@0.3.0
├── link@0.31.0
├── markdown-preview@0.157.1
├── metrics@0.53.1
├── notifications@0.62.1
├── one-dark-syntax@1.1.2
├── one-dark-ui@1.1.9
├── one-light-syntax@1.1.2
├── one-light-ui@1.1.9
├── open-on-github@0.40.0
├── package-generator@0.41.0
├── settings-view@0.232.3
├── snippets@1.0.1
├── solarized-dark-syntax@0.39.0
├── solarized-light-syntax@0.23.0
├── spell-check@0.65.0
├── status-bar@0.80.0
├── styleguide@0.45.0
├── symbols-view@0.110.1
├── tabs@0.88.0
├── timecop@0.33.0
├── tree-view@0.198.1
├── update-package-dependencies@0.10.0
├── welcome@0.33.0
├── whitespace@0.32.1
└── wrap-guide@0.38.1

D:\Work\atom\packages (18)
├── activate-power-mode@0.4.1
├── atom-beautify@0.28.22
├── emmet@2.4.1
├── ex-mode@0.8.0
├── file-icons@1.6.14
├── git-plus@5.13.0
├── highlight-selected@0.11.2
├── jslint@1.5.1
├── linter@1.11.3
├── linter-eslint@6.0.0
├── merge-conflicts@1.3.7
├── minimap@4.19.0
├── pigments@0.24.1
├── SquirrelTemp
├── symbols-tree-view@0.11.0
├── terminal-plus@0.14.5
├── vim-mode@0.64.0
└── wordcount@2.6.0

**Comment by irrationalistic** [comment] 2016-03-11 17:09
Awesome! Thanks for sending that over. It may take me a bit to track down any potential conflicts since that's a big list. If you have the capacity you could try disabling a few of them at a time and see if any of them directly cause Tasks to stop working :)

**Comment by yalishizhude** [comment] 2016-03-13 07:26
The list includes two kinds of packages:the first part packages are atom origin packages,the second are installed by me~I suspect these customized~

**Comment by billglover** [comment] 2016-04-28 13:24
I had a similar issue and can confirm a conflict with the [graphviz-preview](https://atom.io/packages/graphviz-preview) plugin. I've raised an issue as in that particular case the keymaps aren't limited to a data-grammar (see: Issue [#17](https://github.com/jumpkick/graphviz-preview/issues/28)).

In your case, you don't have the graphviz-preview plugin installed but I strongly suspect the issue is going to be similar.

**Comment by vidoardes** [comment] 2016-05-31 11:11
Ctrl-Enter is a default key bind for 'newline below' it's just conflicting with the base key bindings. This won't work unless ToDo list uses different keybindings unfortunatly

**Comment by irrationalistic** [comment] 2016-06-29 03:12
It should automatically select the grammar based on file type! But it is possible there is a keymap collision somewhere :)

**Comment by irrationalistic** [comment] 2016-10-30 07:36
Going to close this for now :) Feel free to re-open if the issue persists

**Closed by irrationalistic** 2016-10-30 07:36 UTC
